# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daed2d17a35eb59f5e67951a80b3cfe7f735c36ffa36a2ddebf69cb4cf9c38ba2569c063ad95e373b8a939aeb8f414a03d1c5a08be16102f04c6b050ea587b0b

test:
  secret_key_base: 1fba763d02aa1323e964db718129553119b3fb3d471d2aef77c04009f33ebf7990551d1bafd21179302127ad5c283097c16a2d043cd60680197a14f6ca00737f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
